# Generated by Django 4.2 on 2024-09-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_estudiantes_descripcion_estudiantes_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='foto',
        ),
        migrations.AddField(
            model_name='estudiantes',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
