# Generated by Django 4.2 on 2024-09-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_remove_estudiantes_foto_estudiantes_fotos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='fotos',
            new_name='foto',
        ),
    ]
