# Generated by Django 4.2 on 2024-09-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_rename_fotos_estudiantes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
